apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  PGDB_HOST: postgres.db.svc.cluster.local
  PGDB_USER: myuser
  PGDB_NAME: mydb
  REDIS_HOST: redis.redis.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: app
type: Opaque
data:
  PGDB_PASSWORD: bXlwYXNzd29yZA==


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: jinitus/flask-app:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: app
spec:
  selector:
    app: flask
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
